# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'LiberApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  # Pods for LiberApp

  #target 'LiberApp-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
  #end

  #target 'LiberAppTests' do
   # inherit! :search_paths
    # Pods for testing
  #end

end

#target 'LiberApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LiberApp-tvOS

 # target 'LiberApp-tvOSTests' do
 #   inherit! :search_paths
    # Pods for testing
  #end

#end
